Get rid of `WireFmt` and `RuntimeContext` in `OperationContainer`
twitter/summingbird pull request #697
Opened 2016-10-15 01:41 UTC by ttim

In this PR I removed `WireFmt` and `RuntimeContext` type parameters from `OperationContainer`. 

Main reason to do that was to make `OperationContainer` composable and responsible only for how to do computations on inputs. Therefore `WireFmt` moved to places which wraps `OperationContainer` in Storm.

`RuntimeContext` wasn't really used anywhere and I removed it for simplicity.

2016-10-15 06:57 UTC, johnynek requested changes
This looks like a nice simplification. 5 type parameters is probably a hint you let things get to complex.

2016-10-15 06:57 UTC, johnynek commented on summingbird-online/src/main/scala/com/twitter/summingbird/online/executor/IntermediateFlatMap.scala
> +  override def cleanup() { lockedOp.get.close }
Can we avoid procedure syntax here? `(): Unit = lockedOp.get.close` will do.

2016-10-15 06:57 UTC, johnynek commented on summingbird-online/src/main/scala/com/twitter/summingbird/online/executor/OperationContainer.scala
> +  def init() {}
Let's avoid deprecated procedure syntax and below.

2016-10-15 07:10 UTC, johnynek approved these changes
:+1:

2016-10-15 07:10 UTC, ttim commented on summingbird-online/src/main/scala/com/twitter/summingbird/online/executor/OperationContainer.scala
> +  def init() {}
Done

2016-10-21 17:07 UTC, jnievelt approved these changes
👍

2016-10-21 17:09 UTC, merged