Summingbird changes for Algebird 0.13.0
twitter/summingbird pull request #715
Opened 2017-02-16 18:01 UTC by piyushnarang

Noticed that the Algebird bump broke SB in a couple of places. We might need to also bump Scalding as part of this (which I can do when we have a release out).

2017-02-16 21:53 UTC, piyushnarang commented
@pankajroark / @johnynek / @ttim - please take a look when you can, thanks.

2017-02-16 22:11 UTC, johnynek requested changes

2017-02-16 22:11 UTC, johnynek commented on summingbird-batch-hadoop/src/test/scala/com/twitter/summingbird/batch/HDFSStateLaws.scala
> +  def leftClosedRightOpenInterval(low: Timestamp, high: Timestamp) = Interval.leftClosedRightOpen[Timestamp](low, high)
can we put a type on the result here? `Interval[Timestamp]`

2017-02-16 22:19 UTC, piyushnarang commented on summingbird-batch-hadoop/src/test/scala/com/twitter/summingbird/batch/HDFSStateLaws.scala
> +  def leftClosedRightOpenInterval(low: Timestamp, high: Timestamp) = Interval.leftClosedRightOpen[Timestamp](low, high)
sure

2017-02-16 22:24 UTC, johnynek commented
👍

2017-02-16 22:26 UTC, ttim approved these changes

2017-02-16 22:26 UTC, ttim commented on summingbird-batch-hadoop/src/test/scala/com/twitter/summingbird/batch/HDFSStateLaws.scala
> +import java.util.{TimeZone, UUID}
nit: I think it should be with spaces (I think it's where your IDEA style settings going against our scalafmt setup).

2017-02-16 22:26 UTC, johnynek approved these changes

2017-02-16 22:30 UTC, piyushnarang commented on summingbird-batch-hadoop/src/test/scala/com/twitter/summingbird/batch/HDFSStateLaws.scala
> +import java.util.{TimeZone, UUID}
yeah seems like the Twitter defaults are set to not include the space :-).

2018-02-15 00:45 UTC, johnynek commented
looks like develop already has this. closing.

2018-02-15 00:45 UTC, closed without merging