Improve memoization to deal with diamonds better
twitter/summingbird pull request #753
Opened 2018-02-08 01:57 UTC by johnynek

In large summingbird graphs, merges can cause exponential runtime in planning because we repeatedly call on the state function on both sides of the merge.

We had a partial solution for this, which worked to make sure the data was not incorrect, but there is a second outer layer: computing what the acceptable time range is. This was the layer that was not memoized, and it was making it take forever to plan for us.

2018-02-08 02:00 UTC, johnynek commented
@ttim can you take a look?

2018-02-08 18:28 UTC, ttim commented
@johnynek I'll take a look later today!

2018-02-09 09:48 UTC, ttim requested changes
Unrelated to your change I'm not quite understand comment before `memoize` function. It says you need to do this memoization for correctness but I can't see how. Do we build `PipeFactory` more than once?

2018-02-09 09:48 UTC, ttim commented on summingbird-scalding/src/main/scala/com/twitter/summingbird/scalding/ScaldingPlatform.scala
> +  def memoize[T](pf: PlannerOutput[FlowProducer[T]]): PlannerOutput[FlowProducer[T]] = {
Can we put `PipeFactor[T]` back here?

2018-02-09 09:48 UTC, ttim commented on summingbird-scalding/src/main/scala/com/twitter/summingbird/scalding/ScaldingPlatform.scala
> +  def memoizePlan[A](pf: PlannerOutput[A]): PlannerOutput[A] = {
I think generic `memoize(StateWithError)` is simpler to understand.

2018-02-09 09:48 UTC, ttim commented on summingbird-scalding/src/main/scala/com/twitter/summingbird/scalding/ScaldingPlatform.scala
> +  def memoizePlan[A](pf: PlannerOutput[A]): PlannerOutput[A] = {
This function doesn't memoize failures?

2018-02-09 09:48 UTC, ttim commented on summingbird-scalding/src/main/scala/com/twitter/summingbird/scalding/ScaldingPlatform.scala
> +    memoizePlan(pf).map { rdr =>
Is `memoizePlan(pf).map { ... as before ... }` has different semantic with this code?

2018-02-09 09:48 UTC, ttim commented on summingbird-scalding/src/main/scala/com/twitter/summingbird/scalding/ScaldingPlatform.scala
> +  def getOrElseUpdate(a: A, b: => B): B =
Can be removed

2018-02-09 18:04 UTC, johnynek commented on summingbird-scalding/src/main/scala/com/twitter/summingbird/scalding/ScaldingPlatform.scala
> +  def memoize[T](pf: PlannerOutput[FlowProducer[T]]): PlannerOutput[FlowProducer[T]] = {
It was needlessly constraining the type. This works for any T. `PipeFactory[T] == PlannerOutput[FlowProducer[TimedPipe[T]]]` so I didn't want to limit it.

2018-02-09 18:05 UTC, johnynek commented on summingbird-scalding/src/main/scala/com/twitter/summingbird/scalding/ScaldingPlatform.scala
> +  def memoizePlan[A](pf: PlannerOutput[A]): PlannerOutput[A] = {
it does not memoize failures.

2018-02-09 18:06 UTC, johnynek commented on summingbird-scalding/src/main/scala/com/twitter/summingbird/scalding/ScaldingPlatform.scala
> +    memoizePlan(pf).map { rdr =>
Previously, we didn't memoize the state computation, just the reader inside. The semantics are the same, but this removes an exponential blowup on graphs that merge back into themselves repeatedly (similar to the problem with a naive implementation of fibonacci).

2018-02-09 18:16 UTC, ttim commented on summingbird-scalding/src/main/scala/com/twitter/summingbird/scalding/ScaldingPlatform.scala
> +  def memoize[T](pf: PlannerOutput[FlowProducer[T]]): PlannerOutput[FlowProducer[T]] = {
Makes sense, looks better this way.

2018-02-09 18:20 UTC, ttim commented on summingbird-scalding/src/main/scala/com/twitter/summingbird/scalding/ScaldingPlatform.scala
> +    memoizePlan(pf).map { rdr =>
Oh, I see. Basically you do `memoizeReader(Reader[I, O]) -> Reader[I, O]`. Then I prefer to have it extracted and then what you want is `memoizeState(pf).map(memoizeReader)`.

2018-02-09 18:25 UTC, johnynek commented
@ttim I made the changes you requested. Can you take another look?

2018-02-09 18:32 UTC, ttim approved these changes
I think with `memoizeReader` this would be better but I'm good either way.

2018-02-09 18:46 UTC, merged

2018-02-09 18:47 UTC, johnynek commented
Thanks for the review @ttim